export const ARXIV_CATEGORIES = [
    // COMPUTER SCIENCE
    { value: 'cs.AI', label: 'Artificial Intelligence (cs.AI)' },
    { value: 'cs.CL', label: 'Computation & Language (cs.CL)' },
    { value: 'cs.CV', label: 'Computer Vision (cs.CV)' },
    { value: 'cs.LG', label: 'Machine Learning (cs.LG)' },
    { value: 'cs.SE', label: 'Software Engineering (cs.SE)' },
    { value: 'cs.RO', label: 'Robotics (cs.RO)' },
    { value: 'cs.CR', label: 'Cryptography and Security (cs.CR)' },
    { value: 'cs.DS', label: 'Data Structures and Algorithms (cs.DS)' },
    { value: 'cs.DB', label: 'Databases (cs.DB)' },
    { value: 'cs.DC', label: 'Distributed, Parallel, and Cluster Computing (cs.DC)' },
    { value: 'cs.HC', label: 'Human-Computer Interaction (cs.HC)' },
    { value: 'cs.IR', label: 'Information Retrieval (cs.IR)' },
    { value: 'cs.NI', label: 'Networking and Internet Architecture (cs.NI)' },
    { value: 'cs.OS', label: 'Operating Systems (cs.OS)' },
    { value: 'cs.PL', label: 'Programming Languages (cs.PL)' },
    { value: 'cs.SI', label: 'Social and Information Networks (cs.SI)' },
    { value: 'cs.CY', label: 'Computers and Society (cs.CY)' },

    // PHYSICS
    { value: 'astro-ph', label: 'Astrophysics (astro-ph)' },
    { value: 'cond-mat', label: 'Condensed Matter (cond-mat)' },
    { value: 'gr-qc', label: 'General Relativity and Quantum Cosmology (gr-qc)' },
    { value: 'hep-ex', label: 'High Energy Physics - Experiment (hep-ex)' },
    { value: 'hep-lat', label: 'High Energy Physics - Lattice (hep-lat)' },
    { value: 'hep-ph', label: 'High Energy Physics - Phenomenology (hep-ph)' },
    { value: 'hep-th', label: 'High Energy Physics - Theory (hep-th)' },
    { value: 'math-ph', label: 'Mathematical Physics (math-ph)' },
    { value: 'nlin', label: 'Nonlinear Sciences (nlin)' },
    { value: 'nucl-ex', label: 'Nuclear Experiment (nucl-ex)' },
    { value: 'nucl-th', label: 'Nuclear Theory (nucl-th)' },
    { value: 'physics', label: 'Physics (physics)' },
    { value: 'quant-ph', label: 'Quantum Physics (quant-ph)' },

    // MATH
    { value: 'math.AG', label: 'Algebraic Geometry (math.AG)' },
    { value: 'math.AT', label: 'Algebraic Topology (math.AT)' },
    { value: 'math.AP', label: 'Analysis of PDEs (math.AP)' },
    { value: 'math.CT', label: 'Category Theory (math.CT)' },
    { value: 'math.CA', label: 'Classical Analysis and ODEs (math.CA)' },
    { value: 'math.CO', label: 'Combinatorics (math.CO)' },
    { value: 'math.GT', label: 'Geometric Topology (math.GT)' },
    { value: 'math.HO', label: 'History and Overview (math.HO)' },
    { value: 'math.IT', label: 'Information Theory (math.IT)' },
    { value: 'math.LO', label: 'Logic (math.LO)' },
    { value: 'math.MP', label: 'Mathematical Physics (math.MP)' },
    { value: 'math.NT', label: 'Number Theory (math.NT)' },
    { value: 'math.NA', label: 'Numerical Analysis (math.NA)' },
    { value: 'math.PR', label: 'Probability (math.PR)' },
    { value: 'math.ST', label: 'Statistics Theory (math.ST)' },

    // BIOLOGY (q-bio)
    { value: 'q-bio.BM', label: 'Biomolecules (q-bio.BM)' },
    { value: 'q-bio.GN', label: 'Genomics (q-bio.GN)' },
    { value: 'q-bio.MN', label: 'Molecular Networks (q-bio.MN)' },
    { value: 'q-bio.NC', label: 'Neurons and Cognition (q-bio.NC)' },
    { value: 'q-bio.OT', label: 'Other Quantitative Biology (q-bio.OT)' },
    { value: 'q-bio.PE', label: 'Populations and Evolution (q-bio.PE)' },
    { value: 'q-bio.QM', label: 'Quantitative Methods (q-bio.QM)' },

    // QUANTITATIVE FINANCE (q-fin)
    { value: 'q-fin.CP', label: 'Computational Finance (q-fin.CP)' },
    { value: 'q-fin.EC', label: 'Economics (q-fin.EC)' },
    { value: 'q-fin.GN', label: 'General Finance (q-fin.GN)' },
    { value: 'q-fin.MF', label: 'Mathematical Finance (q-fin.MF)' },
    { value: 'q-fin.PM', label: 'Portfolio Management (q-fin.PM)' },
    { value: 'q-fin.PR', label: 'Pricing of Securities (q-fin.PR)' },
    { value: 'q-fin.RM', label: 'Risk Management (q-fin.RM)' },
    { value: 'q-fin.ST', label: 'Statistical Finance (q-fin.ST)' },
    { value: 'q-fin.TR', label: 'Trading and Market Microstructure (q-fin.TR)' },

    // STATISTICS (stat)
    { value: 'stat.AP', label: 'Applications (stat.AP)' },
    { value: 'stat.CO', label: 'Computation (stat.CO)' },
    { value: 'stat.ML', label: 'Machine Learning (stat.ML)' },
    { value: 'stat.ME', label: 'Methodology (stat.ME)' },
    { value: 'stat.OT', label: 'Other Statistics (stat.OT)' },
    { value: 'stat.TH', label: 'Statistics Theory (stat.TH)' }
]
