export const BOOKS = [
    // Finance & Economics
    "The Intelligent Investor by Benjamin Graham",
    "Thinking, Fast and Slow by Daniel Kahneman",
    "Principles by Ray Dalio",
    "The Psychology of Money by Morgan Housel",
    "A Random Walk Down Wall Street by Burton Malkiel",
    "Capital in the Twenty-First Century by Thomas Piketty",
    "The Wealth of Nations by Adam Smith",
    "Poor Charlie's Almanack by Charlie Munger",
    "Flash Boys by Michael Lewis",
    "Zero to One by Peter Thiel",
    "The Lean Startup by Eric Ries",
    "Shoe Dog by Phil Knight",
    "Liar's Poker by Michael Lewis",
    "Fooled by Randomness by Nassim Nicholas Taleb",
    "The Black Swan by Nassim Nicholas Taleb",
    "Antifragile by Nassim Nicholas Taleb",
    "Skin in the Game by Nassim Nicholas Taleb",
    "Good to Great by Jim Collins",
    "The Innovator's Dilemma by Clayton Christensen",
    "Thinking in Bets by Annie Duke",

    // Artificial Intelligence & Computer Science
    "Superintelligence by Nick Bostrom",
    "Life 3.0 by Max Tegmark",
    "The Alignment Problem by Brian Christian",
    "Code by Charles Petzold",
    "The Pragmatic Programmer by Andrew Hunt and David Thomas",
    "Clean Code by Robert C. Martin",
    "Gödel, Escher, Bach by Douglas Hofstadter",
    "The Information by James Gleick",
    "Weapons of Math Destruction by Cathy O'Neil",
    "Algorithms to Live By by Brian Christian and Tom Griffiths",
    "Structure and Interpretation of Computer Programs by Harold Abelson and Gerald Jay Sussman",
    "Design Patterns by Erich Gamma et al.",
    "Artificial Intelligence: A Modern Approach by Stuart Russell and Peter Norvig",
    "The Master Algorithm by Pedro Domingos",
    "Deep Learning by Ian Goodfellow, Yoshua Bengio, and Aaron Courville",
    "Human Compatible by Stuart Russell",
    "The Soul of a New Machine by Tracy Kidder",
    "Hackers: Heroes of the Computer Revolution by Steven Levy",
    "The Mythical Man-Month by Frederick P. Brooks Jr.",
    "Hooked by Nir Eyal",

    // Biology & Evolution
    "The Selfish Gene by Richard Dawkins",
    "Sapiens by Yuval Noah Harari",
    "Guns, Germs, and Steel by Jared Diamond",
    "The Emperor of All Maladies by Siddhartha Mukherjee",
    "The Gene by Siddhartha Mukherjee",
    "Behave by Robert Sapolsky",
    "Thinking in Systems by Donella Meadows",
    "The Origin of Species by Charles Darwin",
    "On Growth and Form by D'Arcy Wentworth Thompson",
    "The Blind Watchmaker by Richard Dawkins",
    "The Vital Question by Nick Lane",
    "Power, Sex, Suicide by Nick Lane",
    "Lifespan by David Sinclair",
    "The Immortal Life of Henrietta Lacks by Rebecca Skloot",
    "Entangled Life by Merlin Sheldrake",
    "A Crack in Creation by Jennifer Doudna and Samuel Sternberg",
    "The Body Keeps the Score by Bessel van der Kolk",
    "What is Life? by Erwin Schrödinger",
    "The Double Helix by James D. Watson",
    "Genome by Matt Ridley",

    // Astronomy & Physics
    "A Brief History of Time by Stephen Hawking",
    "Cosmos by Carl Sagan",
    "Astrophysics for People in a Hurry by Neil deGrasse Tyson",
    "The Elegant Universe by Brian Greene",
    "The Fabric of the Cosmos by Brian Greene",
    "Seven Brief Lessons on Physics by Carlo Rovelli",
    "The Order of Time by Carlo Rovelli",
    "Reality Is Not What It Seems by Carlo Rovelli",
    "Something Deeply Hidden by Sean Carroll",
    "The Big Picture by Sean Carroll",
    "QED: The Strange Theory of Light and Matter by Richard Feynman",
    "Surely You're Joking, Mr. Feynman! by Richard Feynman",
    "The Character of Physical Law by Richard Feynman",
    "Pale Blue Dot by Carl Sagan",
    "The First Three Minutes by Steven Weinberg",
    "Black Holes and Baby Universes by Stephen Hawking",
    "The Hidden Reality by Brian Greene",
    "Parallel Worlds by Michio Kaku",
    "Hyperspace by Michio Kaku",
    "The Demon-Haunted World by Carl Sagan",

    // Philosophy & Deep Thinking
    "Meditations by Marcus Aurelius",
    "Letters from a Stoic by Seneca",
    "Man's Search for Meaning by Viktor E. Frankl",
    "The Republic by Plato",
    "Nicomachean Ethics by Aristotle",
    "Beyond Good and Evil by Friedrich Nietzsche",
    "Thus Spoke Zarathustra by Friedrich Nietzsche",
    "Critique of Pure Reason by Immanuel Kant",
    "Being and Time by Martin Heidegger",
    "Tao Te Ching by Laozi",
    "The Art of War by Sun Tzu",
    "Zen and the Art of Motorcycle Maintenance by Robert M. Pirsig",
    "The Righteous Mind by Jonathan Haidt",
    "Thinking, Fast and Slow by Daniel Kahneman",
    "Influence: The Psychology of Persuasion by Robert B. Cialdini",
    "Flow: The Psychology of Optimal Experience by Mihaly Csikszentmihalyi",
    "Atomic Habits by James Clear",
    "Deep Work by Cal Newport",
    "Ego Is the Enemy by Ryan Holiday",
    "The Obstacle Is the Way by Ryan Holiday"
];

export const TOPICS = [
    // Finance & Economics
    "The Efficient Market Hypothesis",
    "Modern Portfolio Theory",
    "Fractional Reserve Banking",
    "The Gold Standard vs Fiat Currency",
    "Quantitative Easing and Central Banks",
    "The Black-Scholes Model",
    "Game Theory in Economics",
    "The Tragedy of the Commons",
    "Nash Equilibrium",
    "Keynesian vs Austrian Economics",
    "Hyperinflation Mechanisms",
    "Derivatives and Collateralized Debt Obligations",
    "Venture Capital Deal Structures",
    "The Capital Asset Pricing Model (CAPM)",
    "Behavioral Economics and Cognitive Biases",
    "Cryptocurrency Consensus Mechanisms (PoW vs PoS)",
    "Smart Contracts and Decentralized Finance",
    "The Petrodollar System",
    "Supply Chain Economics",
    "Universal Basic Income",

    // Artificial Intelligence & Computer Science
    "Transformer Neural Networks",
    "Backpropagation and Gradient Descent",
    "Reinforcement Learning from Human Feedback (RLHF)",
    "P vs NP Problem",
    "Turing Completeness",
    "Public Key Cryptography (RSA)",
    "Zero-Knowledge Proofs",
    "Quantum Computing Principles",
    "Convolutional Neural Networks (CNNs)",
    "Generative Adversarial Networks (GANs)",
    "The Halting Problem",
    "MapReduce and Distributed Computing",
    "Consensus Algorithms (Paxos/Raft)",
    "Vector Databases and High-Dimensional Space",
    "Markov Decision Processes",
    "Attention Mechanisms in NLP",
    "Self-Supervised Learning",
    "Diffusion Models (Image Generation)",
    "Neuromorphic Computing",
    "Algorithmic Complexity (Big O Notation)",

    // Biology & Evolution
    "CRISPR-Cas9 Gene Editing",
    "The Central Dogma of Molecular Biology",
    "Epigenetics",
    "Natural Selection and Genetic Drift",
    "Mitochondrial Evolution (Endosymbiotic Theory)",
    "Telomeres and Aging",
    "The Human Microbiome",
    "Action Potentials in Neurons",
    "Neuroplasticity",
    "Protein Folding Mechanisms",
    "Stem Cells and Cell Differentiation",
    "Apoptosis (Programmed Cell Death)",
    "The Immune System: T-Cells and B-Cells",
    "Horizontal Gene Transfer",
    "Kin Selection and Inclusive Fitness",
    "Punctuated Equilibrium",
    "RNA World Hypothesis",
    "Synthetic Biology",
    "Circadian Rhythms",
    "The Endocrine System and Hormonal Regulation",

    // Astronomy & Physics
    "General Relativity (Spacetime Curvature)",
    "Quantum Entanglement",
    "The Heisenberg Uncertainty Principle",
    "String Theory",
    "Dark Matter and Dark Energy",
    "Black Hole Thermodynamics (Hawking Radiation)",
    "The Standard Model of Particle Physics",
    "Nuclear Fusion in Stars",
    "The Cosmic Microwave Background",
    "Inflationary Cosmology",
    "Special Relativity (Time Dilation)",
    "The Double-Slit Experiment",
    "Superconductivity",
    "Bose-Einstein Condensates",
    "The Fermi Paradox",
    "Loop Quantum Gravity",
    "Neutrino Oscillations",
    "Gravitational Waves",
    "The Holographic Principle",
    "Thermodynamics (The Laws)",

    // Philosophy & Deep Concepts
    "Determinism vs Free Will",
    "The Simulation Hypothesis",
    "Utilitarianism vs Deontology",
    "Nihilism and Existentialism",
    "The Ship of Theseus",
    "Occam's Razor",
    "The Trolley Problem",
    "Epistemology (Theory of Knowledge)",
    "Solipsism",
    "The Absurd (Camus)",
    "Stoicism (Dichotomy of Control)",
    "Plato's Allegory of the Cave",
    "Pascal's Wager",
    "The Categorical Imperative (Kant)",
    "Phenomenology",
    "Panpsychism",
    "The Problem of Evil",
    "Dialectical Materialism",
    "The Veil of Ignorance (John Rawls)",
    "Paradox of Tolerance"
];
